yoda_event_homepage:
    pattern:  /events/{name}/{count}
    defaults: { _controller: YodaEventBundle:Default:index }

YodaEventBundle_event:
        resource: "@YodaEventBundle/Resources/config/routing/event.yml"
        prefix:   /event